# This workflow builds the Docker image, generates an SBOM, and signs the image.
# It now also includes a vulnerability scanning step using Grype.
name: Build, SBOM, Sign, and Scan

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-sbom-sign-scan: # Renamed the job for clarity
    runs-on: ubuntu-latest

    # NOTE: Granting all permissions is NOT a security best practice.
    # This is done here to help diagnose permission issues in our lab environment.
    permissions:
      contents: write # Grant write access to contents
      packages: write # Grant write access to packages
      id-token: write # Allow OpenID Connect (OIDC) token issuance for Sigstore
      security-events: write # Grant write access to security events
      actions: write # Grant write access to actions
      checks: write # Grant write access to checks
      deployments: write # Grant write access to deployments
      discussions: write # Grant write access to discussions
      issues: write # Grant write access to issues
      pages: write # Grant write access to pages
      pull-requests: write # Grant write access to pull requests
      repository-projects: write # Grant write access to repository projects
      statuses: write # Grant write access to statuses

    steps:
    - name: Checkout code
      # Action to check out our repository code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      # Action to set up Buildx, a Docker component for building images
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      # Log in to the GitHub Container Registry where we will push the image
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      # Build and immediately push the tagged image to GitHub Container Registry
      id: build-image # We give this step an ID to reference its outputs
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true # Push the image to the registry
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}

    - name: Install Cosign
      # Install the Cosign tool
      uses: sigstore/cosign-installer@v3.5.0
      with:
        cosign-release: 'v2.2.3' # Specify a Cosign version for reproducibility

    - name: Sign the Container Image with Cosign
      # Use keyless signing to simplify our lab
      # The COSIGN_EXPERIMENTAL environment variable is sometimes needed for keyless
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign sign --yes ghcr.io/${{ github.repository }}@${{ steps.build-image.outputs.digest }}

    - name: Pull Docker Image for Analysis
      # Explicitly pull the image using the authenticated Docker daemon on the runner
      # This ensures the image is available locally for Syft to analyze
      run: docker pull ghcr.io/${{ github.repository }}@${{ steps.build-image.outputs.digest }}

    - name: Generate SBOM with Syft
      # Run Syft as a Docker container to analyze our image
      # Mount the Docker socket to allow Syft access to the daemon
      # Mount the workspace to save the SBOM file to the runner's filesystem
      # Analyze the image and output SBOM to a file in the mounted workspace
      run: |
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v ${{ github.workspace }}:/workspace \
          anchore/syft:latest \
          ghcr.io/${{ github.repository }}@${{ steps.build-image.outputs.digest }} \
          -o cyclonedx-json=/workspace/sbom.json

    - name: Run Vulnerability Scan with Grype
      # Run Grype as a Docker container to scan the SBOM file
      # Mount the workspace to access the sbom.json file and save the report
      # Output the report in SARIF format for GitHub Advanced Security integration
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          anchore/grype:latest \
          sbom:/workspace/sbom.json \
          -o sarif=/workspace/vulnerability-report.sarif

    - name: Upload SARIF report
      # Upload the SARIF vulnerability report to GitHub Advanced Security
      # This requires the 'security-events: write' permission
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: vulnerability-report.sarif

    - name: Upload Vulnerability Report artifact (Optional - for raw report)
      # Upload the raw vulnerability report file as a workflow artifact
      # This allows us to download and review the report directly
      uses: actions/upload-artifact@v4
      with:
        name: vulnerability-report
        path: vulnerability-report.sarif # We can also change output format to .json
        